image: maven:3.6.3-jdk-8

before_script:
  - apt-get update
  - ldd /usr/local/bin/chromedriver
  - apt-get -y install libglib2.0-0
  - apt-get install -y unzip
  - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/local/bin/chromedriver
  - chmod +x /usr/local/bin/chromedriver

test:
  script:
    - mvn test