image: maven:3.6.3-jdk-8

before_script:
  - apt-get update
    #  - apt-get -y install libglib2.0-0
#  - sudo apt-get install libnss3
  - apt-get install -y unzip
  - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/local/bin/chromedriver
  - chmod +x /usr/local/bin/chromedriver
  - # List the required libraries
  - required_libs=$(ldd /usr/local/bin/chromedriver | awk '{if (match($3,"/")){ printf("%s ",$3); }}')

    # Install the necessary packages
  - for lib in $required_libs; do apt-get -y install $(dpkg -S $lib | awk '{sub(":"," "); print $1}'); done



test:
  script:
    - mvn test